# Generated by Django 4.2.8 on 2024-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='sequenceFiles/')),
                ('name', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('owner', models.CharField(default='', max_length=255)),
                ('rights', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
