# Generated by Django 5.0.4 on 2024-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='driver_images/')),
                ('age', models.IntegerField()),
                ('license_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20)),
                ('issued_year', models.IntegerField()),
                ('driver_class', models.CharField(max_length=50)),
            ],
        ),
    ]
