# Generated by Django 5.0.4 on 2024-05-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_driver_id_alter_driver_issued_year_crime'),
    ]

    operations = [
    ]
