# Generated by Django 5.0.4 on 2024-05-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20240501_1219'),
    ]

    operations = [
    ]
